### ISSUE TITLE
Default config file not installed

### ISSUE THREAD

**Issue by flatcap** [neomutt/homebrew-neomutt#12]
I've just received an email (paraphrased):

> When Homebrew installs Mutt, it puts a default `muttrc` in the Home folder
> The NeoMutt Homebrew doesn't

Can we, for now, put the autogenerated `doc/Muttrc` in place?

**Comment by alexpearce** [comment]
I can't see anything in the `mutt.rb` formula that would perform such a copy, and the diff between `mutt.rb` and `neomutt.rb` isn't any more enlightening.

Is the user sure that it's Homebrew putting the `muttrc` file there? I don't know of any Homebrew formula that adds files to the user's home directory (because I think it would be dangerous to do so: what do you do with that file on `brew uninstall <formula>`?)

**Comment by flatcap** [comment]
> I can't see anything in the mutt.rb formula that would perform such a copy

OK, thanks for investigating.

---

_Aside_

In Linux, packages can put sample files in `/etc/skel` which will be copied
when a new user account is created.

> what do you do with that file on brew uninstall \<formula\>

RPM: If the user's altered a config file, then on uninstall it'll be renamed to `.rpmsave`
Debian: Also has a purge option, on uninstall, to delete old config.

**Comment by flatcap** [comment]
User agrees that Mutt probably didn't install it.
Thanks.
