### ISSUE TITLE
Enable more features by default

### ISSUE THREAD

**Issue by alexpearce** [neomutt/homebrew-neomutt#16]
There are some features that are not enabled by default when building NeoMutt. Some are general and apply also to mutt, such as `--with-s-lang`, whilst others are NM specific, such as `--with-notmuch`.

@ludovicchabant [recently commented](https://github.com/neomutt/homebrew-neomutt/issues/14#issuecomment-252446520):

> I just started using Neomutt and it took me a little time to realize that the sidebar patch wasn't applied by default... I may be mistaken but aren't those patches the whole point of using Neomutt instead of vanilla Mutt? Is there a reason to not include those patches by default?

I am inclined to agree that the sidebar patch should be included by default, but I'm less certain about the others. Personally, I always include `--with-notmuch` as well as the sidebar, but that requires a additional dependency, so it seems more 'invasive' to include that by default.

Is there anything else people would like to see always included?

**Comment by telemachus** [comment]
Unless I'm confused as of 1.7.0 [mutt has merged the sidebar patch](http://www.mutt.org/doc/UPDATING), though it's not visible by default.

For whatever it's worth, I would prefer neomutt to provide options rather than defaults. I.e., I'd rather things stay opt-in.

If you do go the other way, I hope it's still possible to opt out. Thanks.

**Comment by alexpearce** [comment]
This might fixed by 53f1c2a, which updates to 20170602 where a few build flags become enabled by default, such as `--with-sidebar`. This is probably sufficiently 'default' for most people, so I'll close this.
